name: i6 CI frontend pipeline

# main 브랜치에 push나 pull request 발생 시 이 workflow가 실행
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Ubuntu OS에서 실행
    runs-on: ubuntu-latest

    steps:
      # 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Docker Hub에 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker 이미지 빌드
      - name: Build docker image and push
        uses: docker/build-push-action@v2
        with:
          context: ./front/healthcare
          file: ./front/healthcare/Dockerfile
          platforms: linux/arm64, linux/arm64
          # 이미지 푸시
          push: true
          tags: |
            ${{ secrets.DOCKER_REPOSITORY_FRONTEND }}:latest
            # SHA 해시를 사용해 커밋별로 고유한 태그를 생성하고 푸시. 
            ${{ secrets.DOCKER_REPOSITORY_FRONTEND }}:${{ github.sha }}

        # 푸시된 docker 이미지를 다시 docker hub에서 pull해서 이미지가 제대로 업로드 되었는지 확인
      - name: Verify Frontend Docker Hub
        # 이전 푸시한 커밋의 SHA 해시 태그로 이미지를 다운로드해 검증.
        run: docker pull ${{ secrets.DOCKER_REPOSITORY_FRONTEND }}:${{ github.sha }}
